### ISSUE TITLE
Chatty heads improvements

### ISSUE THREAD

**Issue by Xiao-MoMi** [MineInAbyss/Chatty#40]
![image](https://user-images.githubusercontent.com/70987828/198335372-9d16a6d2-5083-41ae-bc5b-6ef4383a4f51.png)

 ![image](https://user-images.githubusercontent.com/70987828/198335938-d288818b-5042-475a-b748-1d2061a86ebf.png)
I think use /font to replace font:default would be better :>

**Comment by Boy0000** [comment]
doesnt really matter if closing the old font or using the new one
its just cuz the component doesnt close tags automatically

**Comment by Xiao-MoMi** [comment]
yes, but sometimes it confuses
![image](https://user-images.githubusercontent.com/70987828/198343655-ce3dd6ce-a37c-434d-b686-3aac65567328.png)
![image](https://user-images.githubusercontent.com/70987828/198343676-eb68764b-80fd-4979-bab7-ca4059a9baef.png)

So i have to close the two tags by doing this
![image](https://user-images.githubusercontent.com/70987828/198343799-58d0bcbd-a0d3-4e78-9a2f-7d41d93a4198.png)

**Comment by Boy0000** [comment]
though i dont personally like this solution ill just append a component with </font> as paper doesnt let me close all tags in a component otherwise afaik

**Comment by Boy0000** [comment]
Fixed in [0.4.3](https://github.com/MineInAbyss/Chatty/releases/tag/v0.4.3)
