### ISSUE TITLE
Duplicate messages from discord to minecraft 

### ISSUE THREAD

**Issue by Taiyou06** [MineInAbyss/Chatty#41]
![javaw_ntbuGMCtoY](https://user-images.githubusercontent.com/77050201/201754897-5f1eec9d-8ce4-4f02-baaa-e4a32f97b124.jpg)
![image](https://user-images.githubusercontent.com/77050201/201754917-97248bab-8609-4784-9c9b-bc412e22cc16.png)

emotes (and sometimes messages) gets sent twice 
here's the latest log
[latest.log](https://github.com/MineInAbyss/Chatty/files/10006595/latest.log)

i can send more information if needed.

**Comment by Boy0000** [comment]
for logs use https://hastebin.com or something similar, rarely do people wanna download files
this might be fixed in latest release
